Using https://www.kaggle.com/cyannani123/keras-cellular-image-classification as test example

In [1]:
import os
import sys
import numpy as np
import pandas as pd
import tensorflow as tf
import joblib

In [2]:
from tqdm import tqdm

In [3]:
sys.path.append('../scripts')

In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])

In [6]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [8]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [9]:
from data_v2 import augment
from data_v2 import get_center_box
from data_v2 import get_random_subbox
from data_v2 import ImgGen

Loading test and train data.

Will load directly from zip for now.

In [10]:
train_data_all = pd.read_csv("../data/train.csv")
print("Shape of train_data_all:", train_data_all.shape)


Shape of train_data_all: (36517, 5)


In [11]:
train_data_all[['cell_line','exp']]=list(train_data_all.experiment.str.split('-'))

Võtame esialgu ainul HUVEC liini

In [12]:
train_data_all=train_data_all.loc[train_data_all.cell_line=='HUVEC',:]

In [13]:
train_data_all.head()

id_code experiment  plate well      sirna cell_line exp
7750  HUVEC-01_1_B03   HUVEC-01      1  B03  sirna_403     HUVEC  01
7751  HUVEC-01_1_B04   HUVEC-01      1  B04  sirna_348     HUVEC  01
7752  HUVEC-01_1_B05   HUVEC-01      1  B05  sirna_678     HUVEC  01
7753  HUVEC-01_1_B06   HUVEC-01      1  B06   sirna_39     HUVEC  01
7754  HUVEC-01_1_B07   HUVEC-01      1  B07  sirna_355     HUVEC  01

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [14]:
train_data_strat=train_data_all.groupby('sirna',group_keys=False).apply(lambda x: x.sample(frac=0.1).reset_index(drop=True))

In [10]:
sirna_label_encoder_sample_1 = LabelEncoder().fit(train_data_strat.sirna)

NameError: name 'LabelEncoder' is not defined

In [ ]:
train_gen = ImgGen(train_data_strat,batch_size=16,preprocess=get_center_box,shuffle=True,label_encoder=sirna_label_encoder_sample_1, path=f'{data_path}/train/',cache=True)